//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_sharecapital_tbl
    {
        public decimal id { get; set; }
        public Nullable<decimal> cfid { get; set; }
        public string issuedsharecapital { get; set; }
        public string nominalamoutpershare { get; set; }
        public string shareclass { get; set; }
        public string authorisedsharecapital { get; set; }
    }
}
