//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_agree_tbl
    {
        public decimal cfid { get; set; }
        public Nullable<long> agree { get; set; }
        public string nonthirdparties { get; set; }
        public string incorporationtype { get; set; }
        public string companypacktype { get; set; }
        public string paymenttype { get; set; }
        public string name { get; set; }
        public string companyname { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string addressline3 { get; set; }
        public Nullable<decimal> postcode { get; set; }
        public Nullable<decimal> phonenumber { get; set; }
        public string email { get; set; }
        public string username { get; set; }
    }
}
