//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_corporatesubscriber_tbl
    {
        public decimal id { get; set; }
        public Nullable<decimal> cfid { get; set; }
        public string companyname { get; set; }
        public string companydirector { get; set; }
        public string registerofficeaddress { get; set; }
        public string addressline2 { get; set; }
        public string addressline3 { get; set; }
        public Nullable<decimal> postalcode { get; set; }
        public string country { get; set; }
        public string numberofshare { get; set; }
    }
}
