//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_usermst_tbl
    {
        public decimal user_id { get; set; }
        public string user_code { get; set; }
        public string user_fullname { get; set; }
        public string user_emailid { get; set; }
        public string user_username { get; set; }
        public string user_pwd { get; set; }
        public string user_department { get; set; }
        public string user_phone { get; set; }
        public string user_role { get; set; }
        public int user_active { get; set; }
        public int user_delete { get; set; }
        public System.DateTime user_createdon { get; set; }
    }
}
