//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_secretary_tbl
    {
        public decimal id { get; set; }
        public Nullable<decimal> cfid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string addressline3 { get; set; }
        public string postalcode { get; set; }
        public string country { get; set; }
        public string companyname { get; set; }
        public Nullable<decimal> companynumber { get; set; }
        public string companydirector { get; set; }
        public string companyregionaloffice { get; set; }
        public string companyaddressline1 { get; set; }
        public string companyaddressline2 { get; set; }
        public string compnaypostal { get; set; }
        public string compnaycountry { get; set; }
    }
}
