//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_statusmst_tbl
    {
        public decimal cfid { get; set; }
        public string company_name { get; set; }
        public string form_status { get; set; }
        public string pdf_filename { get; set; }
        public string pdf_filepath { get; set; }
        public System.DateTime createdon { get; set; }
    }
}
