//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_addressdetails_tbl
    {
        public decimal id { get; set; }
        public Nullable<decimal> cfid { get; set; }
        public string roaddressline1 { get; set; }
        public string roaddressline2 { get; set; }
        public string oraddressline3 { get; set; }
        public Nullable<decimal> ropostalcode { get; set; }
        public string caaddressline1 { get; set; }
        public string caaddressline2 { get; set; }
        public string caaddressline3 { get; set; }
        public Nullable<decimal> capostalcode { get; set; }
        public string roisalsothebusinessorcaaddress { get; set; }
    }
}
