//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_ticketreply_tbl
    {
        public decimal reply_id { get; set; }
        public string tciket_number { get; set; }
        public string reply_email { get; set; }
        public string reply_name { get; set; }
        public string reply_details { get; set; }
        public string reply_files { get; set; }
        public string reply_status { get; set; }
        public Nullable<System.DateTime> reply_date { get; set; }
    }
}
