//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_ticketmst_tbl
    {
        public decimal ticket_id { get; set; }
        public string ticket_number { get; set; }
        public string ticket_email { get; set; }
        public string ticket_name { get; set; }
        public string ticket_business { get; set; }
        public string ticket_phoneno { get; set; }
        public string ticket_extension { get; set; }
        public string ticket_helptopic { get; set; }
        public string ticket_issuesummary { get; set; }
        public string ticket_details { get; set; }
        public string ticket_files { get; set; }
        public string ticket_initial_status { get; set; }
        public Nullable<System.DateTime> ticket_createdate { get; set; }
        public string ticket_final_status { get; set; }
        public Nullable<System.DateTime> ticket_finaldate { get; set; }
    }
}
