//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cls_companyincorporation_tbl
    {
        public decimal id { get; set; }
        public Nullable<decimal> cfid { get; set; }
        public string firstchoice { get; set; }
        public string secondchoice { get; set; }
        public string thirdchoice { get; set; }
        public string principalactivity { get; set; }
        public string additionalwording { get; set; }
        public string companytype { get; set; }
    }
}
